package com.swift.example;

import com.swift.ApiException;
import com.swift.api.CancelTransactionsApi;
import com.swift.model.CamtA0600102;
import com.swift.model.CamtA0600202;

public class CancelTransactionsApiExample {

	public static void main(String[] args) {
		
		CancelTransactionsApi apiInstance = new CancelTransactionsApi();
        String laUApplicationID = "001"; // String | ID that identifies the application generationg the API and used by the gpi Connector to retrieve the related LAU keys
        String laUVersion = "1.0"; // String | version of the LAUSigned header. Mandatory. \"1.0\" for this first release
        String laUCallTime = "2018-03-23T15:56:26.728Z"; // String | timestamp in UTC of the API call in the format YYYY-MM-DDTHH:MM:SS.sssZ
        String laURequestNonce = "e802ab96-bb3a-4965-9139-5214b9f0f074"; // String | a random value generated by the client. Provided with the request and copied by the gpi Connector on the response
        String laUSigned = "(ApplAPIKey=yVGhKiV5z1ZGdaqFXoZ8AiSA9n5CrY6B),(RBACRole=[FullViewer/Scope/cclabeb0])"; // String | service specific HTTP headers
        String laUSignature = "U1khA8h9Lm1PqzB99fG6uw=="; // String | contains the LAU signature, base64 ecoded
        Boolean signatureRequired = true; // Boolean | a field indicating that a Signature is required
        String xApiKey = "yVGhKiV5z1ZGdaqFXoZ8AiSA9n5CrY6B"; // String | An API key given to your application to authenticate against the sandbox URL
        CamtA0600102 requestBody = new CamtA0600102(); // CamtA0600102 | Cancel Transaction Request
        try {
            CamtA0600202 result = apiInstance.cancelTransactionsPost(laUApplicationID, laUVersion, laUCallTime, laURequestNonce, laUSigned, laUSignature, signatureRequired, xApiKey, requestBody);
            System.out.println(result);
        } catch (ApiException e) {
            System.err.println("Exception when calling CancelTransactionsApi#cancelTransactionsPost");
            e.printStackTrace();
        }

	}

}
