/*
 * gpi API
 * Move your app forward with the gpi API
 *
 * OpenAPI spec version: 2.0.2
 * Contact: Li.JIE@swift.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.GetInvalidEventsRequest;
import java.io.IOException;

/**
 * ISO 20022 JSON Schema GetInvalidEventsRequest (camt.a05.001.03) Generated by SWIFT Standards 2018-07-16 09:05:02
 */
@ApiModel(description = "ISO 20022 JSON Schema GetInvalidEventsRequest (camt.a05.001.03) Generated by SWIFT Standards 2018-07-16 09:05:02")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-15T16:12:10.361-04:00")
public class CamtA0500103 {
  @SerializedName("get_invalid_events_request")
  private GetInvalidEventsRequest getInvalidEventsRequest = null;

  public CamtA0500103 getInvalidEventsRequest(GetInvalidEventsRequest getInvalidEventsRequest) {
    this.getInvalidEventsRequest = getInvalidEventsRequest;
    return this;
  }

   /**
   * Get getInvalidEventsRequest
   * @return getInvalidEventsRequest
  **/
  @ApiModelProperty(value = "")
  public GetInvalidEventsRequest getGetInvalidEventsRequest() {
    return getInvalidEventsRequest;
  }

  public void setGetInvalidEventsRequest(GetInvalidEventsRequest getInvalidEventsRequest) {
    this.getInvalidEventsRequest = getInvalidEventsRequest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CamtA0500103 camtA0500103 = (CamtA0500103) o;
    return Objects.equals(this.getInvalidEventsRequest, camtA0500103.getInvalidEventsRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(getInvalidEventsRequest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CamtA0500103 {\n");
    
    sb.append("    getInvalidEventsRequest: ").append(toIndentedString(getInvalidEventsRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

