/*
 * gpi API
 * Move your app forward with the gpi API
 *
 * OpenAPI spec version: 2.0.2
 * Contact: Li.JIE@swift.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CamtA0600102;
import io.swagger.client.model.CamtA0600202;
import io.swagger.client.model.ErrorCode;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CancelTransactionsApi
 */
@Ignore
public class CancelTransactionsApiTest {

    private final CancelTransactionsApi api = new CancelTransactionsApi();

    
    /**
     * Cancel Transactions
     *
     * This API informs the tracker about the cancellation of a given transaction
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cancelTransactionsPostTest() throws ApiException {
        String laUApplicationID = null;
        String laUVersion = null;
        String laUCallTime = null;
        String laURequestNonce = null;
        String laUSigned = null;
        String laUSignature = null;
        Boolean signatureRequired = null;
        String xApiKey = null;
        CamtA0600102 requestBody = null;
        CamtA0600202 response = api.cancelTransactionsPost(laUApplicationID, laUVersion, laUCallTime, laURequestNonce, laUSigned, laUSignature, signatureRequired, xApiKey, requestBody);

        // TODO: test validations
    }
    
}
