/*
 * gpi API
 * Move your app forward with the gpi API
 *
 * OpenAPI spec version: 2.0.2
 * Contact: Li.JIE@swift.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CamtA0500103;
import io.swagger.client.model.CamtA0500203;
import io.swagger.client.model.ErrorCode;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GetInvalidEventsApi
 */
@Ignore
public class GetInvalidEventsApiTest {

    private final GetInvalidEventsApi api = new GetInvalidEventsApi();

    
    /**
     * Get Invalid Events
     *
     * This API is a payment events&#39; query to get invalid events for payment transactions within a given time frame. An event is either a payment or a status confirmation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getInvalidEventsPostTest() throws ApiException {
        String laUApplicationID = null;
        String laUVersion = null;
        String laUCallTime = null;
        String laURequestNonce = null;
        String laUSigned = null;
        String laUSignature = null;
        String xApiKey = null;
        CamtA0500103 requestBody = null;
        CamtA0500203 response = api.getInvalidEventsPost(laUApplicationID, laUVersion, laUCallTime, laURequestNonce, laUSigned, laUSignature, xApiKey, requestBody);

        // TODO: test validations
    }
    
}
