/*
 * Tracker API v2
 * Move your app forward with the gpi API
 *
 */

package com.swift.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ISO 20022 JSON Schema UpdatePaymentStatusRequest (camt.a01.001.03) Generated by SWIFT Standards 2018-07-16 09:05:02
 */
@ApiModel(description = "ISO 20022 JSON Schema UpdatePaymentStatusRequest (camt.a01.001.03) Generated by SWIFT Standards 2018-07-16 09:05:02")
public class CamtA0100103 {
  @SerializedName("update_payment_status_request")
  private UpdatePaymentStatusRequest updatePaymentStatusRequest = null;

  public CamtA0100103 updatePaymentStatusRequest(UpdatePaymentStatusRequest updatePaymentStatusRequest) {
    this.updatePaymentStatusRequest = updatePaymentStatusRequest;
    return this;
  }

   /**
   * Get updatePaymentStatusRequest
   * @return updatePaymentStatusRequest
  **/
  @ApiModelProperty(value = "")
  public UpdatePaymentStatusRequest getUpdatePaymentStatusRequest() {
    return updatePaymentStatusRequest;
  }

  public void setUpdatePaymentStatusRequest(UpdatePaymentStatusRequest updatePaymentStatusRequest) {
    this.updatePaymentStatusRequest = updatePaymentStatusRequest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CamtA0100103 camtA0100103 = (CamtA0100103) o;
    return Objects.equals(this.updatePaymentStatusRequest, camtA0100103.updatePaymentStatusRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(updatePaymentStatusRequest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CamtA0100103 {\n");

    sb.append("    updatePaymentStatusRequest: ").append(toIndentedString(updatePaymentStatusRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
