/*
 * Tracker API v2
 * Move your app forward with the gpi API
 *
 */

package com.swift.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ISO 20022 JSON Schema GetChangedPaymentTransactionsRequest (camt.a04.001.03) Generated by SWIFT Standards 2018-07-16 09:05:02
 */
@ApiModel(description = "ISO 20022 JSON Schema GetChangedPaymentTransactionsRequest (camt.a04.001.03) Generated by SWIFT Standards 2018-07-16 09:05:02")
public class CamtA0400103 {
  @SerializedName("get_changed_payment_transactions_request")
  private GetChangedPaymentTransactionsRequest getChangedPaymentTransactionsRequest = null;

  public CamtA0400103 getChangedPaymentTransactionsRequest(GetChangedPaymentTransactionsRequest getChangedPaymentTransactionsRequest) {
    this.getChangedPaymentTransactionsRequest = getChangedPaymentTransactionsRequest;
    return this;
  }

   /**
   * Get getChangedPaymentTransactionsRequest
   * @return getChangedPaymentTransactionsRequest
  **/
  @ApiModelProperty(value = "")
  public GetChangedPaymentTransactionsRequest getGetChangedPaymentTransactionsRequest() {
    return getChangedPaymentTransactionsRequest;
  }

  public void setGetChangedPaymentTransactionsRequest(GetChangedPaymentTransactionsRequest getChangedPaymentTransactionsRequest) {
    this.getChangedPaymentTransactionsRequest = getChangedPaymentTransactionsRequest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CamtA0400103 camtA0400103 = (CamtA0400103) o;
    return Objects.equals(this.getChangedPaymentTransactionsRequest, camtA0400103.getChangedPaymentTransactionsRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(getChangedPaymentTransactionsRequest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CamtA0400103 {\n");

    sb.append("    getChangedPaymentTransactionsRequest: ").append(toIndentedString(getChangedPaymentTransactionsRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
