/*
 * gpi API v2
 * Move your app forward with the gpi API
 *
 */


package com.swift.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.swift.model.GetPaymentTransactionDetailsRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ISO 20022 JSON Schema GetPaymentTransactionDetailsRequest (camt.a02.001.03) Generated by SWIFT Standards 2018-07-16 09:05:02
 */
@ApiModel(description = "ISO 20022 JSON Schema GetPaymentTransactionDetailsRequest (camt.a02.001.03) Generated by SWIFT Standards 2018-07-16 09:05:02")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-20T13:44:06.319-05:00")
public class CamtA0200103 {
  @SerializedName("get_payment_transaction_details_request")
  private GetPaymentTransactionDetailsRequest getPaymentTransactionDetailsRequest = null;

  public CamtA0200103 getPaymentTransactionDetailsRequest(GetPaymentTransactionDetailsRequest getPaymentTransactionDetailsRequest) {
    this.getPaymentTransactionDetailsRequest = getPaymentTransactionDetailsRequest;
    return this;
  }

   /**
   * Get getPaymentTransactionDetailsRequest
   * @return getPaymentTransactionDetailsRequest
  **/
  @ApiModelProperty(value = "")
  public GetPaymentTransactionDetailsRequest getGetPaymentTransactionDetailsRequest() {
    return getPaymentTransactionDetailsRequest;
  }

  public void setGetPaymentTransactionDetailsRequest(GetPaymentTransactionDetailsRequest getPaymentTransactionDetailsRequest) {
    this.getPaymentTransactionDetailsRequest = getPaymentTransactionDetailsRequest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CamtA0200103 camtA0200103 = (CamtA0200103) o;
    return Objects.equals(this.getPaymentTransactionDetailsRequest, camtA0200103.getPaymentTransactionDetailsRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(getPaymentTransactionDetailsRequest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CamtA0200103 {\n");

    sb.append("    getPaymentTransactionDetailsRequest: ").append(toIndentedString(getPaymentTransactionDetailsRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
