/*
 * gpi API
 * Move your app forward with the gpi API
 *
 * OpenAPI spec version: 2.0.2
 * Contact: Li.JIE@swift.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.swift.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets PaymentCancellationStatusReason3Code
 */
@JsonAdapter(PaymentCancellationStatusReason3Code.Adapter.class)
public enum PaymentCancellationStatusReason3Code {
  
  S003("S003"),
  
  S004("S004");

  private String value;

  PaymentCancellationStatusReason3Code(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PaymentCancellationStatusReason3Code fromValue(String text) {
    for (PaymentCancellationStatusReason3Code b : PaymentCancellationStatusReason3Code.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<PaymentCancellationStatusReason3Code> {
    @Override
    public void write(final JsonWriter jsonWriter, final PaymentCancellationStatusReason3Code enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PaymentCancellationStatusReason3Code read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PaymentCancellationStatusReason3Code.fromValue(String.valueOf(value));
    }
  }
}

